// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4fLz9_Uac6i6N9wqhtiCY4iqdAFbc9G8',
    appId: '1:11776777903:web:ed43dbc41e490d99767e5a',
    messagingSenderId: '11776777903',
    projectId: 'iha-database',
    authDomain: 'iha-database.firebaseapp.com',
    databaseURL: 'https://iha-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iha-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4D1A2SDxj9iFDoLfMaFxStAVh79PRCDA',
    appId: '1:11776777903:android:93a96f2304cbea07767e5a',
    messagingSenderId: '11776777903',
    projectId: 'iha-database',
    databaseURL: 'https://iha-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iha-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyv76HyH3R-70sMcMsyOFEmoEyHXf30s',
    appId: '1:11776777903:ios:8300d2fce730f62c767e5a',
    messagingSenderId: '11776777903',
    projectId: 'iha-database',
    databaseURL: 'https://iha-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iha-database.appspot.com',
    iosClientId: '11776777903-ok86tffauc1rcthbvtl8ikui7ae9kof6.apps.googleusercontent.com',
    iosBundleId: 'com.example.artunFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcyv76HyH3R-70sMcMsyOFEmoEyHXf30s',
    appId: '1:11776777903:ios:8300d2fce730f62c767e5a',
    messagingSenderId: '11776777903',
    projectId: 'iha-database',
    databaseURL: 'https://iha-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iha-database.appspot.com',
    iosClientId: '11776777903-ok86tffauc1rcthbvtl8ikui7ae9kof6.apps.googleusercontent.com',
    iosBundleId: 'com.example.artunFlutterProject',
  );
}
